# *****************************************************************************
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# ******************************************************************************

FROM jupyterlab_image

ARG NB_USER="jovyan"

EXPOSE 8888

USER root

RUN usermod -aG sudo $NB_USER

COPY jupyter_notebook_config.py /etc/jupyter/jupyter_notebook_config.py

#Prepearing Start script
COPY jupyterlab_run.sh /jupyterlab_run.sh
RUN  sed -i 's|CONF_PATH|/etc/jupyter/jupyter_notebook_config.py|' /jupyterlab_run.sh \
  && chmod +x /jupyterlab_run.sh

RUN apt update && apt install -y vim netcat-openbsd git

RUN pip install --upgrade jupyterlab-git

RUN echo "ENABLED PLUGINS:" && \
    jupyter serverextension list && \
    jupyter labextension list


USER $NB_USER

ENTRYPOINT ["/jupyterlab_run.sh", "-d"]