# *****************************************************************************
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# ******************************************************************************

# Default values for dlab-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
labels: {}

ui:
  service_base_name: ${service_base_name}
  os: ${os}
  bucketName: ${ssn_bucket_name}
  image:
    repository: epamdlab/ui
    tag: '0.1-aws'
    pullPolicy: Always
  service:
    type: NodePort
    #  port: 58443
    http_port: 58080
    https_port: 58443
  ingress:
    enabled: true
    host: ${ssn_k8s_alb_dns_name}
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  mongo:
    host: ${mongo_service_name}
    port: ${mongo_port}
    username: ${mongo_user}
    db_name: ${mongo_db_name}
  provisionService:
    host: ${provision_service_host}
  keycloak:
    auth_server_url: http://${ssn_k8s_alb_dns_name}/auth
    redirect_uri: http://${ssn_k8s_alb_dns_name}/
