{{- /*
  # *****************************************************************************
  #
  # Licensed to the Apache Software Foundation (ASF) under one
  # or more contributor license agreements.  See the NOTICE file
  # distributed with this work for additional information
  # regarding copyright ownership.  The ASF licenses this file
  # to you under the Apache License, Version 2.0 (the
  # "License"); you may not use this file except in compliance
  # with the License.  You may obtain a copy of the License at
  #
  #   http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing,
  # software distributed under the License is distributed on an
  # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  # KIND, either express or implied.  See the License for the
  # specific language governing permissions and limitations
  # under the License.
  #
  # ******************************************************************************
  */ -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datalab-ui.fullname" . }}
  labels: {{ include "datalab-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "datalab-ui.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "datalab-ui.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-db-password
                  key: password
            - name: SSN_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ssn-keystore-password
                  key: password
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client-secret
                  key: client_secret
            - name: KEYCLOAK_AUTH_URL
              value: {{ .Values.ui.keycloak.auth_server_url }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: ui-conf
              mountPath: /root/ssn.yml
              subPath: ssn
              readOnly: true
            - name: ui-conf
              mountPath: /root/self-service.yml
              subPath: self-service
              readOnly: true
            - mountPath: "/root/step-certs"
              name: ui-tls
              readOnly: true
      volumes:
        - name: ui-conf
          configMap:
            name: {{ include "datalab-ui.fullname" . }}-ui-conf
            defaultMode: 0644
            items:
              - key: ssn.yml
                path: ssn
              - key: self-service.yml
                path: self-service
        - name: ui-tls
          secret:
            secretName: {{ include "datalab-ui.fullname" . }}-tls

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
