#!/usr/bin/expect -f

set i 0; foreach n $argv {set "p[incr i]" $n}

set timeout 60
eval spawn $p1 login
match_max 100000

expect "Username"
send "$p2\r"

expect "Password"
send "$p3\r"

expect "Email"
send "$p4\r"

expect {
   timeout      exit 1
}